services:
  flask_app:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
      MYSQL_DB: bookstore_db
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: techpro1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
